title: Dr. Anas M. R. AlSobeh
description: Assistant Professor & Program Coordinator, SIUC — AI · Cybersecurity · Software Engineering
url: https://aalosbeh.github.io
theme: minima
minima:
  skin: classic
  social_links:
    - { platform: orcid, user_url: "https://orcid.org/0000-0002-1506-7924" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/" }
    - { platform: researchgate, user_url: "https://www.researchgate.net/" }
google_analytics:  # (optional) add your GA id here e.g., G-XXXXXXX
show_excerpts: true
header_pages:
  - index.md
  - publications.md
  - teaching.md
  - projects.md
  - service.md
  - cv.md
  - resume.md
  - contact.md
# Customize footer line
footer_content: "© { site.time | date: '%Y' } Dr. Anas M. R. AlSobeh — AI + Cybersecurity + Software Engineering"
# Plugins: keep empty for GitHub Pages compatibility without extra deps
plugins: []
