title: Dr. Anas M. R. AlSobeh
description: Assistant Professor & Program Coordinator, SIUC — AI + Cybersecurity + Software Engineering
theme: minima
minima:
  social_links:
    - { platform: orcid,  user_url: "https://orcid.org/0000-0002-1506-7924" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/" }
    - { platform: researchgate, user_url: "https://www.researchgate.net/" }
plugins: []
